#!/usr/bin/env python
import cgi, os
import cgitb; cgitb.enable()

print "Content-type: text/html\n\n"

form = cgi.FieldStorage()
message = ""

# A nested FieldStorage instance holds the file
try:
   fileitem = form['file']
   pack = form['pack'].value

   valid_packs = "main player".split()

   # Test if the file was uploaded
   if fileitem.filename and pack in valid_packs:

      # strip leading path from file name to avoid directory traversal attacks
      fn = os.path.basename(fileitem.filename).replace(" ","")
      open('/var/www/vhosts/pomme.us/docs/img/' + pack + '/' + fn, 'wb').write(fileitem.file.read())
      message = 'The file "' + fn + '" was uploaded successfully.<br><img src="/img/' + pack + '/' + fn + '" style="max-width: 300px;max-height:300px;">'
      os.system("/bin/touch /var/www/vhosts/pomme.us/docs/img/NEW_IMAGES")
   else:
      message = 'No file uploaded'
except:
   pass
   
print """<html>
<head>
<link href="/css/staff.css" media="screen, projection" rel="stylesheet" type="text/css" />
</head>
<body>
"""
print file("menu.txt").read()
print """
<hr>
<form enctype="multipart/form-data" action="/cgi-bin/staff/upload" method="post">
<p>Pack:
  <select name="pack">
    <option value="player" selected>Player</option>
    <option value="main">Main</option>
  </select>
</p>
<p>File: <input type="file" name="file"></p>
<p><input type="submit" value="Upload"></p>
</form>
<p>
"""
print message
print """
</p>
</body></html>
"""
